let a=10;
let b=20;
console.log("greater than:", a>b);
console.log("lessthan:",a<b);
console.log("greaterthan or equal to:", a>=b);
console.log("lessthan or equal to:",a<=b);
console.log("andand:", a&&b);
console.log("or:",a||b);
console.log("not:", a|b);
console.log("equal to:",a=b);
let c=1;
console.log("increment:",c++);
console.log(c);
console.log("decrement:",c--);
console.log(c);
console.log("and:",a&b);
console.log("or:",a|b);
console.log("power:",a^c);
console.log(a<<b);
console.log(a>>c);
console.log(~a);
